dmaap.certificateConfig.keyCert: /opt/app/datafile/etc/cert/cert.p12
dmaap.certificateConfig.keyPasswordPath: /opt/app/datafile/etc/cert/p12.pass
dmaap.certificateConfig.trustedCa: /opt/app/datafile/etc/cert/trust.jks
dmaap.certificateConfig.trustedCaPasswordPath: /opt/app/datafile/etc/cert/trust.pass
dmaap.dmaapConsumerConfiguration.consumerGroup: OpenDcae-c12
dmaap.dmaapConsumerConfiguration.consumerId: C12
dmaap.dmaapConsumerConfiguration.timeoutMs: -1
dmaap.security.enableDmaapCertAuth: false
dmaap.security.keyStorePasswordPath: /opt/app/datafile/etc/cert/jks.pass
dmaap.security.keyStorePath: /opt/app/datafile/etc/cert/cert.jks
dmaap.security.trustStorePasswordPath: /opt/app/datafile/etc/cert/trust.pass
dmaap.security.trustStorePath: /opt/app/datafile/etc/cert/trust.jks
service_calls: []
sftp.security.strictHostKeyChecking: true
streams_publishes:
  PM_MEAS_FILES:
    dmaap_info:
      location: loc00
      log_url: https://dmaap-dr-prov/feedlog/1
      password: pmmapper
      publish_url: http://dmaap-dr-prov:8080/publish/1
      publisher_id: 1.85gkg
      username: pmmapper
    type: data_router
streams_subscribes:
  dmaap_subscriber:
    dmaap_info:
      topic_url: http://mr-simulator:3904/events/unauthenticated.VES_NOTIFICATION_OUTPUT
    type: message_router
